// <auto-generated />
using System;
using ColdTrack_Back.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrack_Back.Migrations
{
    [DbContext(typeof(ColdTrackDbContext))]
    [Migration("20260803160215_TaskModule")]
    partial class TaskModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColdTrack_Back.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ColdTrack_Back.Models.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Addition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSeq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ColdTrack_Back.Models.DiscardDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiscardDepartments");
                });

            modelBuilder.Entity("ColdTrack_Back.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7093),
                            Group = "用户管理",
                            Key = "user.read",
                            Name = "用户查看"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7101),
                            Group = "用户管理",
                            Key = "user.create",
                            Name = "用户创建"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7103),
                            Group = "用户管理",
                            Key = "user.update",
                            Name = "用户编辑"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7104),
                            Group = "用户管理",
                            Key = "user.delete",
                            Name = "用户删除"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7106),
                            Group = "用户管理",
                            Key = "user.assign",
                            Name = "用户分配职位"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7109),
                            Group = "部门管理",
                            Key = "department.read",
                            Name = "部门查看"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7110),
                            Group = "部门管理",
                            Key = "department.create",
                            Name = "部门创建"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7112),
                            Group = "部门管理",
                            Key = "department.update",
                            Name = "部门编辑"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7113),
                            Group = "部门管理",
                            Key = "department.delete",
                            Name = "部门删除"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7115),
                            Group = "职位管理",
                            Key = "position.read",
                            Name = "职位查看"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7116),
                            Group = "职位管理",
                            Key = "position.create",
                            Name = "职位创建"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7117),
                            Group = "职位管理",
                            Key = "position.update",
                            Name = "职位编辑"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7118),
                            Group = "职位管理",
                            Key = "position.delete",
                            Name = "职位删除"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7120),
                            Group = "任务管理",
                            Key = "task.read",
                            Name = "任务查看"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7122),
                            Group = "任务管理",
                            Key = "task.create",
                            Name = "任务创建"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7124),
                            Group = "任务管理",
                            Key = "task.update",
                            Name = "任务编辑"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7126),
                            Group = "任务管理",
                            Key = "task.delete",
                            Name = "任务删除"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2026, 8, 3, 16, 2, 14, 995, DateTimeKind.Utc).AddTicks(7128),
                            Group = "系统设置",
                            Key = "role.manage",
                            Name = "角色与权限管理"
                        });
                });

            modelBuilder.Entity("ColdTrack_Back.Models.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Addition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ColdTrack_Back.Models.PositionDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PositionDepartments");
                });

            modelBuilder.Entity("ColdTrack_Back.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 11L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 17L
                        },
                        new
                        {
                            RoleId = "f0874ebd-be74-4a5e-951a-c738f27f6cb8",
                            PermissionId = 18L
                        },
                        new
                        {
                            RoleId = "7d06dcab-5a11-482e-b015-cf5f6569d5a3",
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = "7d06dcab-5a11-482e-b015-cf5f6569d5a3",
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = "7d06dcab-5a11-482e-b015-cf5f6569d5a3",
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = "7d06dcab-5a11-482e-b015-cf5f6569d5a3",
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = "7d06dcab-5a11-482e-b015-cf5f6569d5a3",
                            PermissionId = 14L
                        });
                });

            modelBuilder.Entity("ColdTrack_Back.Models.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssigneeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ColdTrack_Back.Models.UserPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPositions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ColdTrack_Back.Models.TaskItem", b =>
                {
                    b.HasOne("ColdTrack_Back.Models.AppUser", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ColdTrack_Back.Models.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ColdTrack_Back.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ColdTrack_Back.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdTrack_Back.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ColdTrack_Back.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
